SportsStore/Components/CartSummaryViewComponent.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using SportsStore.Models;
using Microsoft.AspNetCore.Mvc;

namespace SportsStore.Components
{
    public class CartSummaryViewComponent : ViewComponent
    {
        private Cart _cart;
        public CartSummaryViewComponent(Cart cart)
        {
            _cart = cart;
        }

        public IViewComponentResult Invoke()
        {
            return View(_cart);
        }
    }
}

SportsStore/Components/NavigationMenuViewComponent.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using SportsStore.Models;

namespace SportsStore.Components
{
    public class NavigationMenuViewComponent:ViewComponent
    {
        private IProductRepository _repository;
        public NavigationMenuViewComponent(IProductRepository repo)
        {
            _repository = repo;
        }
        public IViewComponentResult Invoke()
        {
            ViewBag.SelectedCategory = RouteData?.Values["category"];
            return View(_repository.Products
                .Select(x => x.Category)
                .Distinct()
                .OrderBy(x => x));  
        }
    }
}

SportsStore/Views/Shared/ProductSummary.cshtml
@model  Product
<div>
    <h3>
        <strong>@Model.Name</strong>
        <span class="pull-right label label-primary">
            @Model.Price.ToString("c")
        </span>
    </h3>

    <form id=@Model.ProductID asp-action="AddToCart"
          asp-controller="Cart" method="post">
        <input type="hidden" asp-for="ProductID"/> <!--дублируется свойство модели ProductId-->

        <input type="hidden" name="returnUrl"
           value="@ViewContext.HttpContext.Request.PathAndQuery()" />

        <span class="lead">
            @Model.Description
            <button type="submit" class="btn btn-success btn-sm pull-right">
            Add To Cart
            </button>
        </span>
    </form>
</div>

SportsStore/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link rel="stylesheet" asp-href-include="lib/bootstrap/dist/css/*" />
    <style>
        .input-validation-error {
            border-color: red;
            background-color: #fee;
        }
    </style>

    <script asp-src-include="lib/jquery/**/jquery.min.js"></script>
    <script asp-src-include="lib/jquery-validate/**/jquery.validate.min.js"></script>
    <script asp-src-include="lib/jquery-validation-unobtrusive/**/*.min.js"></script>

</head>

<body class="panel panel-default">
    <div class="panel-heading">
        <h4>
        @ViewBag.Title
        
        <a class="btn btn-sm btn-primary pull-right"
            asp-action="Logout" asp-controller="Account"> Log Out </a>
        </h4>   
        
    </div>
    

    <div class="panel-body">
        @if (TempData["message"] != null)
        {
            <div class="alert alert-success">@TempData["message"]</div>
        }
        @RenderBody()
    </div>
      
</body>
</html>

SportsStore/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>SportsStore</title>
    <link rel="stylesheet" asp-href-include="lib/bootstrap/dist/css/*" />
    <link rel="stylesheet" asp-href-include="lib/fontawesome/css/*.css" />


</head>
<body>
    <div class="navbar navbar-inverse" role="navigation">
        <a class="navbar-brand" href="#">SPORTS STORE</a>
        <div class="pull-right">
            @await Component.InvokeAsync("CartSummary")

        </div>
    </div>
      
    <div class="row panel">
         
        <div id="categories" class="col-xs-3">
            @await Component.InvokeAsync("NavigationMenu")
        </div>
        <div class="col-xs-8">
            @RenderBody()
        </div>
    </div>
</body>
</html>